INSERT INTO `Tags` (tag_id, tag_name) VALUES (0,"Beine");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (1,"hintere Schulter");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (2,"Po");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (3,"Rücken");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (4,"Trapez");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (5,"Brust");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (6,"Bauch");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (7,"Nacken");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (8,"Trizeps");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (9,"Quadrizeps");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (10,"vordere Schulter");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (11,"Waden");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (12,"seitliche Schulter");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (13,"Rückenstrecker");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (14,"Arme");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (15,"Warm-up");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (16,"Bizeps");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (17,"Schulter");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (18,"Hamstrings");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (19,"Latissimus");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (20,"Arme Trizeps");