USE trainings_DB;
INSERT INTO `Tags` (tag_id, tag_name) VALUES (1,"Beine");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (2,"hintere Schulter");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (3,"Po");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (4,"Rücken");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (5,"Trapez");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (6,"Brust");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (7,"Bauch");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (8,"Nacken");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (9,"Trizeps");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (10,"Quadrizeps");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (11,"vordere Schulter");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (12,"Waden");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (13,"seitliche Schulter");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (14,"Rückenstrecker");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (15,"Arme");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (16,"Warm-up");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (17,"Bizeps");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (18,"Schulter");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (19,"Hamstrings");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (20,"Latissimus");
INSERT INTO `Tags` (tag_id, tag_name) VALUES (21,"Arme Trizeps");