version: "3"
services:
  db:
    image: mysql:latest
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - "./scripts/createDB.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/createTables.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./scripts/insertDemoData.sql:/docker-entrypoint-initdb.d/3.sql"
      - "./bck:/var/lib/bck"
