version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - "./scripts/createDB.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/createTables.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./scripts/insertDemoData.sql:/docker-entrypoint-initdb.d/3.sql"
      - "./scripts/createProcedures.sql:/docker-entrypoint-initdb.d/4.sql"
      - "./scripts/createTriggers.sql:/docker-entrypoint-initdb.d/5.sql"
      - "./bck:/var/lib/bck"
  mongo:
    image: mongo:latest
    container_name: ${MONGO_DB_CONTAINER_NAME}
    restart: always
    ports:
      - 27017:${MONGO_DB_PORT}
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PWD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    depends_on:
      - mysql

